In [1]:
import sys, os
import pandas as pd
import numpy as np
import itertools

sys.path.append('../../scripts/2_comparative_analysis')

from compare import compare_pairwise

### Compare MCM with early ARS

In [6]:
output_dir = '../../results/compared_peaks'

ARS_early = pd.read_csv('../../data/references/ARS_early.bed',
                    names=['chr', 'start', 'end', 'center'], sep='\t', header=None)
MCM = pd.read_csv(f'{output_dir}/RDY368_G1_unTr_nT_nC_RDY412_G1_unTr_nT_nC/in_RDY412_G1_unTr_nT_nC_RDY368_G1_unTr_nT_nC_ex.bed', 
                    names=['chr', 'start', 'end', 'center'], sep='\t', header=None)

In [ ]:
origins = compare_pairwise({'ARS': ARS_early},
                            {'MCMs': MCM})
origins

       chr   start     end  center MCMs_start MCMs_end MCMs_center
0     chrI   30946   31183   31064      30919    31069       30994
1     chrI   70300   70469   70384      70281    70431       70356
2     chrI  124349  124597  124473     124411   124561      124486
3     chrI  222880  224046  223463     223963   224113      224038
4    chrII  143658  143745  143702     143655   143805      143730
..     ...     ...     ...     ...        ...      ...         ...
95  chrXVI  260931  261727  261329     261451   261601      261526
96  chrXVI  456563  456810  456686     456713   456863      456788
97  chrXVI  880861  881108  880984        NaN      NaN         NaN
98  chrXVI  932983  933229  933106     933108   933258      933183
99  chrXVI  942084  943032  942558     942362   942512      942437

[100 rows x 7 columns]

In [9]:
origins.to_csv(f'{output_dir}/eARS_with_MCMs_0bp.csv', sep='\t', header=True)

In [11]:
origins = ARS_early.copy()

origins = compare_pairwise({'ARS': ARS_early},
                            {'MCMs': MCM},
                            include_neighbours=150)
origins

Warning: for ARS_id 52 found more than one overlappin interval for MCMs. Saving only first (edit this in the future)

       chr   start     end  center MCMs_start MCMs_end MCMs_center
0     chrI   30946   31183   31064      30919    31069       30994
1     chrI   70300   70469   70384      70281    70431       70356
2     chrI  124349  124597  124473     124411   124561      124486
3     chrI  222880  224046  223463     223963   224113      224038
4    chrII  143658  143745  143702     143655   143805      143730
..     ...     ...     ...     ...        ...      ...         ...
95  chrXVI  260931  261727  261329     261451   261601      261526
96  chrXVI  456563  456810  456686     456713   456863      456788
97  chrXVI  880861  881108  880984     881198   881348      881273
98  chrXVI  932983  933229  933106     933108   933258      933183
99  chrXVI  942084  943032  942558     942362   942512      942437

[100 rows x 7 columns]

In [12]:
origins.to_csv(f'{output_dir}/eARS_with_MCMs_150bp.csv', sep='\t', header=True)