In [ ]:
import sys, os
import pandas as pd
import numpy as np
import itertools

sys.path.append('../../scripts/2_comparative_analysis')

from compare import compare_pairwise

In [7]:
# Load ARS positions from SGD
ARS_df = pd.read_csv('../../data/references/ARS_SGD.bed', names=['chr', 'start', 'end', 'center'], sep='\t')
ARS_df

        chr   start     end  center
0      chrI     707     776     741
1      chrI    7997    8547    8272
2      chrI   30946   31183   31064
3      chrI   41992   42151   42071
4      chrI   70300   70469   70384
..      ...     ...     ...     ...
346  chrXVI  842653  842900  842776
347  chrXVI  850512  850629  850570
348  chrXVI  880861  881108  880984
349  chrXVI  932983  933229  933106
350  chrXVI  942084  943032  942558

[351 rows x 4 columns]

# I. For each ARS, find overlapping peaks from 3 replication factors in different stages of cell cycle.
This script returns table, where each row corresponding to ARS from SGD and columns are coordinates of 1) ARS, 2) Overlapping Mcm2, 3) Mcm4 3) Sld3.
If there is no overlapping peak between ARS and factor, returns NaN.

In [10]:
# Load data for Mcm4
MCM4_as = pd.read_csv('../../results/merged_peaks/RDY368/RDY368_as_unTr_nT_nC.bed', names=['chr', 'start', 'end', 'center'], sep='\t', header=None)
MCM4_G1 = pd.read_csv('../../results/merged_peaks/RDY368/RDY368_G1_unTr_nT_nC.bed', names=['chr', 'start', 'end', 'center'], sep='\t', header=None)
MCM4_S = pd.read_csv('../../results/merged_peaks/RDY368/RDY368_S_unTr_nT_nC.bed', names=['chr', 'start', 'end', 'center'], sep='\t', header=None)
MCM4_G2 = pd.read_csv('../../results/merged_peaks/RDY368/RDY368_G2_unTr_nT_nC.bed', names=['chr', 'start', 'end', 'center'], sep='\t', header=None)

In [12]:
# Load data for Mcm2
MCM2_as = pd.read_csv('../../results/merged_peaks/RDY412/RDY412_as_unTr_nT_nC.bed', names=['chr', 'start', 'end', 'center'], sep='\t', header=None)
MCM2_G1 = pd.read_csv('../../results/merged_peaks/RDY412/RDY412_G1_unTr_nT_nC.bed', names=['chr', 'start', 'end', 'center'], sep='\t', header=None)
MCM2_S = pd.read_csv('../../results/merged_peaks/RDY412/RDY412_S_unTr_nT_nC.bed', names=['chr', 'start', 'end', 'center'], sep='\t', header=None)
MCM2_G2 = pd.read_csv('../../results/merged_peaks/RDY412/RDY412_G2_unTr_nT_nC.bed', names=['chr', 'start', 'end', 'center'], sep='\t', header=None)

In [13]:
# Load data for Sld3
SLD3_as = pd.read_csv('../../results/merged_peaks/RDY342/RDY342_as_unTr_nT_nC.bed', names=['chr', 'start', 'end', 'center'], sep='\t', header=None)
SLD3_G1 = pd.read_csv('../../results/merged_peaks/RDY342/RDY342_G1_unTr_nT_nC.bed', names=['chr', 'start', 'end', 'center'], sep='\t', header=None)
SLD3_S = pd.read_csv('../../results/merged_peaks/RDY342/RDY342_S_unTr_nT_nC.bed', names=['chr', 'start', 'end', 'center'], sep='\t', header=None)
SLD3_G2 = pd.read_csv('../../results/merged_peaks/RDY342/RDY342_G2_unTr_nT_nC.bed', names=['chr', 'start', 'end', 'center'], sep='\t', header=None)

In [14]:
origins = ARS_df.copy()

origins = compare_pairwise({'ARS': origins},
                     {'MCM4_as': MCM4_as})
origins = compare_pairwise({'ARS': origins},
                     {'MCM4_G1': MCM4_G1})
origins = compare_pairwise({'ARS': origins},
                     {'MCM4_S': MCM4_S})
origins = compare_pairwise({'ARS': origins},
                     {'MCM4_G2': MCM4_G2})

origins

,chr,start,end,center,MCM4_as_start,MCM4_as_end,MCM4_as_center,MCM4_G1_start,MCM4_G1_end,MCM4_G1_center,MCM4_S_start,MCM4_S_end,MCM4_S_center,MCM4_G2_start,MCM4_G2_end,MCM4_G2_center
0,chrI,707,776,741,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,chrI,7997,8547,8272,8105,8255,8180.0,8118,8268,8193.0,8117,8267,8192.0,8108,8258,8183.0
2,chrI,30946,31183,31064,30934,31084,31009.0,30912,31062,30987.0,30914,31064,30989.0,30920,31070,30995.0
3,chrI,41992,42151,42071,41956,42106,42031.0,41957,42107,42032.0,41950,42100,42025.0,41962,42112,42037.0
4,chrI,70300,70469,70384,70317,70467,70392.0,70310,70460,70385.0,70328,70478,70403.0,70382,70532,70457.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,chrXVI,842653,842900,842776,842725,842875,842800.0,842725,842875,842800.0,842718,842868,842793.0,842718,842868,842793.0
347,chrXVI,850512,850629,850570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
348,chrXVI,880861,881108,880984,880862,881012,880937.0,NaN,NaN,NaN,880916,881066,880991.0,880913,881063,880988.0
349,chrXVI,932983,933229,933106,933104,933254,933179.0,933113,933263,933188.0,933135,933285,933210.0,933122,933272,933197.0
350,chrXVI,942084,943032,942558,942372,942522,942447.333333,942362,942512,942437.333333,942371,942521,942446.0,942362,942512,942437.75

In [15]:
origins = compare_pairwise({'ARS': origins},
                     {'MCM2_as': MCM2_as})
origins = compare_pairwise({'ARS': origins},
                     {'MCM2_G1': MCM2_G1})
origins = compare_pairwise({'ARS': origins},
                     {'MCM2_S': MCM2_S})
origins = compare_pairwise({'ARS': origins},
                     {'MCM2_G2': MCM2_G2})

origins

,chr,start,end,center,MCM4_as_start,MCM4_as_end,MCM4_as_center,MCM4_G1_start,MCM4_G1_end,MCM4_G1_center,...,MCM2_as_center,MCM2_G1_start,MCM2_G1_end,MCM2_G1_center,MCM2_S_start,MCM2_S_end,MCM2_S_center,MCM2_G2_start,MCM2_G2_end,MCM2_G2_center
0,chrI,707,776,741,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,chrI,7997,8547,8272,8105,8255,8180.0,8118,8268,8193.0,...,8180.0,8118,8268,8193.0,8117,8267,8192.0,8108,8258,8183.0
2,chrI,30946,31183,31064,30934,31084,31009.0,30912,31062,30987.0,...,31009.0,30912,31062,30987.0,30914,31064,30989.0,30920,31070,30995.0
3,chrI,41992,42151,42071,41956,42106,42031.0,41957,42107,42032.0,...,42031.0,41957,42107,42032.0,41950,42100,42025.0,41962,42112,42037.0
4,chrI,70300,70469,70384,70317,70467,70392.0,70310,70460,70385.0,...,70392.0,70310,70460,70385.0,70328,70478,70403.0,70382,70532,70457.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,chrXVI,842653,842900,842776,842725,842875,842800.0,842725,842875,842800.0,...,842800.0,842725,842875,842800.0,842718,842868,842793.0,842718,842868,842793.0
347,chrXVI,850512,850629,850570,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
348,chrXVI,880861,881108,880984,880862,881012,880937.0,NaN,NaN,NaN,...,880937.0,NaN,NaN,NaN,880916,881066,880991.0,880913,881063,880988.0
349,chrXVI,932983,933229,933106,933104,933254,933179.0,933113,933263,933188.0,...,933179.0,933113,933263,933188.0,933135,933285,933210.0,933122,933272,933197.0
350,chrXVI,942084,943032,942558,942372,942522,942447.333333,942362,942512,942437.333333,...,942447.333333,942362,942512,942437.333333,942371,942521,942446.0,942362,942512,942437.75

In [16]:
origins = compare_pairwise({'ARS': origins},
                     {'SLD3_as': SLD3_as})
origins = compare_pairwise({'ARS': origins},
                     {'SLD3_G1': SLD3_G1})
origins = compare_pairwise({'ARS': origins},
                     {'SLD3_S': SLD3_S})
origins = compare_pairwise({'ARS': origins},
                     {'SLD3_G2': SLD3_G2})

origins

Warning: for ARS_id 43 found more than one overlappin interval for SLD3_as. Saving only first (edit this in the future)
Warning: for ARS_id 43 found more than one overlappin interval for SLD3_S. Saving only first (edit this in the future)
Warning: for ARS_id 43 found more than one overlappin interval for SLD3_G2. Saving only first (edit this in the future)

,chr,start,end,center,MCM4_as_start,MCM4_as_end,MCM4_as_center,MCM4_G1_start,MCM4_G1_end,MCM4_G1_center,...,SLD3_as_center,SLD3_G1_start,SLD3_G1_end,SLD3_G1_center,SLD3_S_start,SLD3_S_end,SLD3_S_center,SLD3_G2_start,SLD3_G2_end,SLD3_G2_center
0,chrI,707,776,741,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,chrI,7997,8547,8272,8105,8255,8180.0,8118,8268,8193.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chrI,30946,31183,31064,30934,31084,31009.0,30912,31062,30987.0,...,NaN,NaN,NaN,NaN,30933,31083,31008.0,NaN,NaN,NaN
3,chrI,41992,42151,42071,41956,42106,42031.0,41957,42107,42032.0,...,42063.0,NaN,NaN,NaN,41971,42121,42046.0,42005,42155,42080.0
4,chrI,70300,70469,70384,70317,70467,70392.0,70310,70460,70385.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,chrXVI,842653,842900,842776,842725,842875,842800.0,842725,842875,842800.0,...,NaN,NaN,NaN,NaN,842726,842876,842801.0,NaN,NaN,NaN
347,chrXVI,850512,850629,850570,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
348,chrXVI,880861,881108,880984,880862,881012,880937.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
349,chrXVI,932983,933229,933106,933104,933254,933179.0,933113,933263,933188.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350,chrXVI,942084,943032,942558,942372,942522,942447.333333,942362,942512,942437.333333,...,NaN,942727,942877,942802.5,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
output_dir = '../../results/compared_peaks'
origins.to_csv(f'{output_dir}/ARS_Replication_factors_positions.csv', sep='\t', header=True)

# II. Find overlapping MCM with ARS

In [19]:
# Compare MCMs (overlapped positions between Mcm2 and Mcm4) with ARS with 150bp window
MCM = pd.read_csv(f'{output_dir}/RDY368_G1_unTr_nT_nC_RDY412_G1_unTr_nT_nC/in_RDY412_G1_unTr_nT_nC_RDY368_G1_unTr_nT_nC_ex.bed', names=['chr', 'start', 'end', 'center'], sep='\t', header=None)
origins = ARS_df.copy()

origins = compare_pairwise({'ARS': origins},
                     {'MCMs': MCM}, include_neighbours = 150)
origins.to_csv(f'{output_dir}/ARS_with_MCMs_150bp.csv', sep='\t', header=True)
origins

Warning: for ARS_id 37 found more than one overlappin interval for MCMs. Saving only first (edit this in the future)
Warning: for ARS_id 172 found more than one overlappin interval for MCMs. Saving only first (edit this in the future)

        chr   start     end  center MCMs_start MCMs_end MCMs_center
0      chrI     707     776     741        NaN      NaN         NaN
1      chrI    7997    8547    8272       8119     8269        8194
2      chrI   30946   31183   31064      30919    31069       30994
3      chrI   41992   42151   42071      41961    42111       42036
4      chrI   70300   70469   70384      70281    70431       70356
..      ...     ...     ...     ...        ...      ...         ...
346  chrXVI  842653  842900  842776     842719   842869      842794
347  chrXVI  850512  850629  850570        NaN      NaN         NaN
348  chrXVI  880861  881108  880984     881198   881348      881273
349  chrXVI  932983  933229  933106     933108   933258      933183
350  chrXVI  942084  943032  942558     942362   942512      942437

[351 rows x 7 columns]

In [20]:
origins = ARS_df.copy()

origins = pairwise_comparison({'ARS': origins},
                     {'MCMs': MCM}, include_neighbours = 0)
origins.to_csv(f'{output_dir}/ARS_with_MCMs_0bp.csv', sep='\t', header=True)

In [21]:
print(f"MCM peaks that overlapping with any ARS form SGD: {origins.shape[0] - origins['MCMs_start'].isnull().sum()} ({(origins.shape[0] - origins['MCMs_start'].isnull().sum()) / origins.shape[0] * 100} of SGD origins)")

MCM peaks that overlapping with any ARS form SGD: 291 (82.90598290598291 of SGD origins)