In [1]:
import sys, os
import pandas as pd
import numpy as np
import itertools

sys.path.append('../../scripts/2_comparative_analysis')

from compare import compare_pairwise

In [16]:
# Load data
# Load coomon peaks for MCM2 and MCM4
MCM2_MCM4 = pd.read_csv('../../results/compared_peaks/RDY368_G1_unTr_nT_nC_RDY412_G1_unTr_nT_nC/in_RDY412_G1_unTr_nT_nC_RDY368_G1_unTr_nT_nC_ex.bed', names=['chr', 'start', 'end', 'center'], sep='\t')

# Load ARS SGD
ARS_SGD = pd.read_csv('../../data/references/ARS_late.bed', names=['chr', 'start', 'end', 'center'], sep='\t')

# Load ARS early and late
ARS_early_late = pd.read_csv('../../data/references/SGD_ARS_annot_only_early_late.csv', sep=',')
ARS_early = ARS_early_late[ARS_early_late['Early_late_Yabuki2002'] == 'early'][['chr', 'ARS_left', 'ARS_right', 'ARS_center']]
ARS_early.columns = ['chr', 'start', 'end', 'center']

ARS_late = ARS_early_late[ARS_early_late['Early_late_Yabuki2002'] == 'late'][['chr', 'ARS_left', 'ARS_right', 'ARS_center']]
ARS_late.columns = ['chr', 'start', 'end', 'center']

In [29]:
MCM2_MCM4

        chr   start     end  center
0      chrI    6399    6549    6474
1      chrI    8119    8269    8194
2      chrI   10063   10213   10138
3      chrI   16805   16955   16880
4      chrI   23233   23383   23308
..      ...     ...     ...     ...
767  chrXVI  881198  881348  881273
768  chrXVI  909547  909697  909622
769  chrXVI  929661  929811  929736
770  chrXVI  933108  933258  933183
771  chrXVI  942362  942512  942437

[772 rows x 4 columns]

In [32]:
def check_match(row, factor):
    mask = (factor['chr'] == row['chr']) & \
           (row['center'] + 75 >= factor['start']) & \
           (row['center'] - 75 <= factor['end'])
    return mask.any()

In [35]:
MCM = pd.DataFrame()
MCM['chr'] = MCM2_MCM4['chr']
MCM['center'] = MCM2_MCM4['center']

MCM['ARS_SGD'] = MCM.apply(check_match, axis=1, factor=ARS_SGD).astype(int)
MCM['ARS_early'] = MCM.apply(check_match, axis=1, factor=ARS_early).astype(int)
MCM['ARS_late'] = MCM.apply(check_match, axis=1, factor=ARS_late).astype(int)
MCM

        chr  center  ARS_SGD  ARS_early  ARS_late
0      chrI    6474        0          0         0
1      chrI    8194        0          0         0
2      chrI   10138        0          0         0
3      chrI   16880        0          0         0
4      chrI   23308        0          0         0
..      ...     ...      ...        ...       ...
767  chrXVI  881273        0          0         0
768  chrXVI  909622        0          0         0
769  chrXVI  929736        0          0         0
770  chrXVI  933183        1          0         1
771  chrXVI  942437        1          0         1

[772 rows x 5 columns]

In [20]:
X = compare_pairwise({'MCM': MCM2_MCM4},
                    {'ARS_early': ARS_early})
X

,chr,start,end,center,ARS_early_start,ARS_early_end,ARS_early_center
0,chrI,6399,6549,6474,NaN,NaN,NaN
1,chrI,8119,8269,8194,NaN,NaN,NaN
2,chrI,10063,10213,10138,NaN,NaN,NaN
3,chrI,16805,16955,16880,NaN,NaN,NaN
4,chrI,23233,23383,23308,NaN,NaN,NaN
...,...,...,...,...,...,...,...
767,chrXVI,881198,881348,881273,NaN,NaN,NaN
768,chrXVI,909547,909697,909622,NaN,NaN,NaN
769,chrXVI,929661,929811,929736,NaN,NaN,NaN
770,chrXVI,933108,933258,933183,NaN,NaN,NaN
771,chrXVI,942362,942512,942437,NaN,NaN,NaN